device:
  preference: 'cuda'
  index: null

distributed_training:
  num_processes: 3
  per_gpu_batch_size: 3
  total_batch_size: 9  # per_gpu_batch_size * num_processes
  workers_per_gpu: 6
  training_workers: 18  # workers_per_gpu * num_processes
  validation_workers: 18  # workers_per_gpu * num_processes
  grad_accumulate: 8

optimization:
  base_lr: 1.0e-5
  max_lr: 1.0e-4
  lr: 1.732e-5  # base_lr * sqrt(total_batch_size / per_gpu_batch_size)

training:
  epochs: 100
  timesteps: 4000
  loss_type: "simple"
  sample_delay: 10

experiment:
  project_name: "DEF"
  experiment_name: "init-conditional"
  save_path: "/data/users/jupyter-dam724/def-era/checkpoint/diffusion/init-conditional/"
  operator_checkpoint: "/data/users/jupyter-dam724/def-era/checkpoint/state/..."
  state_checkpoint: null