device:
  preference: 'cuda'
  index: null

distributed_training:
  num_processes: 2
  per_gpu_batch_size: 32
  total_batch_size: 64  # per_gpu_batch_size * num_processes
  workers_per_gpu: 6
  training_workers: 12  # workers_per_gpu * num_processes
  validation_workers: 12  # workers_per_gpu * num_processes
  grad_accumulate: 1

optimization:
  base_lr: 1.0e-5
  max_lr: 1.0e-4
  lr: 1.414e-5  # base_lr * sqrt(total_batch_size / per_gpu_batch_size)

training:
  epochs: 40
  validation_delay: 1
  patience: 10

experiment:
  project_name: "DEF"
  experiment_name: "init-op"
  save_path: "/data/users/jupyter-dam724/def/checkpoint/operator/init-op/"
  from_checkpoint: null